# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=15)),
                ('user_id', models.CharField(max_length=30)),
                ('img', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField()),
                ('write_date', models.CharField(blank=True, max_length=30, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user_id', 'write_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='instagram',
            unique_together=set([('post_id', 'user_id')]),
        ),
    ]
