# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171116_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('sent', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MusicTagPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=100)),
                ('ext_tags', models.CharField(max_length=170, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='musictagplaylist',
            unique_together=set([('code', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='musictag',
            unique_together=set([('code',)]),
        ),
    ]
